version: "3.7"

services:
# service name will be "app"
  app:
# to build the "Dockerfile" image file
    build: .
    container_name: rental-api
    ports:
      - 3333:3333
    volumes:
# workdir specified in "Dockerfile"
      - .:/usr/app
