version: "3.7"

services:
  database_api:
    image: postgres
    container_name: database_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=car_db
    volumes:
      - pgdata:/data/postgres
    network_mode: host
# service name will be "app"
  app:
# to build the "Dockerfile" image file
    build: .
    container_name: rental-api
    ports:
      - 3333:3333
    volumes:
# workdir specified in "Dockerfile"
      - .:/usr/app
      - /usr/app/node_modules
    network_mode: host
volumes:
  pgdata:
    driver: local
